### PR TITLE
Remove $ in code example

### PR DESCRIPTION
**Pull request by clemens-tolboom**
Let's make this copy/paste able.

### CODE REVIEW

**Comment by jlord** [comment]
@clemens-tolboom cool, that would be helpful. Do you think we should make it comment-less so that people can copy and paste the whole thing?

**Comment by clemens-tolboom** [comment]
Comments are fine for the command-line newbies as they can copy-paste and learn through the comments

**Comment by ngoldman** [comment]
```sh
# lines starting with `#` are fine when copy-pasting shell commands, they will be ignored
```

:smile:

**Comment by zeke** [comment]
My zsh doesn't like it:

```
❯ # Clone this repository
zsh: bad pattern: #
```

**Comment by ngoldman** [comment]
Thanks for pointing that out @zeke! It looks this behavior varies depending on the shell you're working with, and whether or not your shell session is set to allow "interactive comments" (just learned all of this after your comment).

From what I'm reading, zsh uses `#` for [pattern removal](http://zsh.sourceforge.net/Guide/zshguide05.html), but also in general comments are not always ignored in interactive shells -- the `interactive_comments` setting changes this behavior (see https://www.gnu.org/software/bash/manual/html_node/Comments.html or http://zsh.sourceforge.net/Intro/intro_16.html). So one should not assume that `#`-style comments can always be copy-pasted into interactive shells. :grin:

**Comment by clemens-tolboom** [comment]
@ngoldman that for elaborating on zsh

My zsh (on Mac) gives `zsh: command not found: #` (which I 'just' ignored :()

Googling myself I found https://thejh.net/misc/website-terminal-copy-paste which made me instantly reluctant to copy/paste to my terminal.

**Comment by jlord** [comment]
Good to know!

So how about we go with the PR as-is, remove the `$` and just make the single lines easier to copypasta and not worry about making the whole block copy-able?

**Comment by ngoldman** [comment]
:sunglasses: :cool:

**Pull request merged**
