### PR TITLE
Change license to CC0

### PR DESCRIPTION
**Pull request by phanect**
We can more easily build our own app based on this code if it is public domain.

Allowance by @johnmuhl, @IonicaBizau and @Shriken might be required too...?

### CODE REVIEW

**Comment by IonicaBizau** [comment]
It's fine from my side. :+1:

**Comment by benogle** [comment]
cc @jlord

**Comment by benogle** [comment]
cc @kevinsawicki

**Comment by jlord** [comment]
Thanks for this suggestion. Yeah, it makes sense to not have to worry about copyright notices when using this to start a new project. I'm :+1: on putting CC0 on a bare bones starter repo like this. 

Note that there are 3 non-GitHub-staff contributors; normally we'd ask for :+1: from each before changing the license, but as these few character contributions are clearly _de minimis_ as can be I think we're ok to go forward.

**Comment by phanect** [comment]
Thanks!

**Pull request merged**
